sudo: false
language: python
os: linux
install:
- &upgrade_python_toolset pip install --upgrade pip setuptools wheel
- pip install tox-travis
- pip install coveralls
script: []
after_success:
- coveralls

jobs:
  fast_finish: true
  include:
  - stage: test
    name: "Python 2.7"
    python: 2.7
    script:
    - tox -e py34
  - stage: test
    name: "Python 3.4"
    python: 3.4
    script:
    - tox -e py34
  - stage: test
    name: "Python 3.5"
    python: 3.5
    script:
    - tox -e py35
  - stage: test
    name: "Python 3.6"
    python: 3.6
    script:
    - tox -e py36
  - stage: test
    name: "Python 3.7"
    python: 3.7
    dist: xenial
    sudo: true
    script:
    - tox -e py37
  - stage: test
    name: "PyPy"
    python: pypy
    script:
    - tox -e pypy
  - stage: test
    name: "PyPy3"
    python: pypy3.5
    script:
    - tox -e pypy3

  - stage: Static analisys
    name: "PyLint"
    python: 3.6
    services: []
    install:
    - *upgrade_python_toolset
    - pip install tox
    script:
    - tox -e pylint
    after_success: skip
  - stage: Static analisys
    name: "Bandit"
    python: 3.6
    services: []
    install:
    - *upgrade_python_toolset
    - pip install tox
    script:
    - tox -e bandit
    after_success: skip
  - stage: Static analisys
    name: "MyPy"
    python: 3.7
    dist: xenial
    sudo: true
    services: []
    install:
    - *upgrade_python_toolset
    - pip install tox
    script:
    - tox -e mypy
    after_success: skip

  - stage: Test cythonized
    name: "Python 3.4"
    python: 3.4
    script:
    - tox -e py34-nocov
    after_success: skip
  - stage: Test cythonized
    name: "Python 3.5"
    python: 3.5
    script:
    - tox -e py35-nocov
    after_success: skip
  - stage: Test cythonized
    name: "Python 3.6"
    python: 3.6
    script:
    - tox -e py36-nocov
    after_success: skip
  - stage: Test cythonized
    name: "Python 3.7"
    python: 3.7
    dist: xenial
    sudo: true
    script:
    - tox -e py37-nocov
    after_success: skip

  - stage: Code style check
    name: "PEP8"
    python: 3.6
    install:
    - *upgrade_python_toolset
    - pip install tox
    script:
    - tox -e pep8
    after_success: skip
  - stage: Code style check
    name: "PEP257"
    python: 3.6
    install:
    - *upgrade_python_toolset
    - pip install tox
    script:
    - tox -e pep257
    after_success: skip

  - stage: deploy
    # This prevents job from appearing in test plan unless commit is tagged:
    if: tag IS present
    # Run on pypy to build not cythonized wheel
    python: pypy3.5
    services:
    - docker
    install:
    - *upgrade_python_toolset
    script:
    - ./tools/run_docker.sh "Advanced_Descriptors"
    before_deploy:
    - pip install -r build_requirements.txt
    - python setup.py bdist_wheel
    deploy:
    - provider: pypi
      # `skip_cleanup: true` is required to preserve binary wheels, built
      # inside of manylinux1 docker container during `script` step above.
      skip_cleanup: true
      user: penguinolog
      password:
        secure: "mG8p4UUzpz9wBdbif68NunjLp3rSED/OJw2Rh1nLBSSNcKtRBVEW4Gm/KYfHHc+kXVB66Nkda+T214kx4WhDk7lVRDKVu7ej0ze2mJX9iYmxhjOt7dcldostPAT8ZFfIvxEpS3UYGCPRbWTdOeeTe3wqz7/boVjC4DZu82nTarBJzApEn5ivtVHMs9bCedmk9Potb3FOiOscjkmEiKSllVQhgHnE/WPBOkfsaSaTCQKeTnqcCqJehNo4ki0cbmtAMpdPoR4DxAlHFK9jFD/W5Pm8s3UMkCer7vTwImINYICuibAIKEKcHdSHXOWJ6FoT21mJdgTWoZQGlAAKw8KV9R8dM6bNazV9iJbM3qUTUEJzyb08miRUf6iKxoPR1MpfqxuZ+ExGHfb0gX/Nu75aNxCSTbQ1YJD/oeXaqRQwpeGmW8vAXB9JSThfiEafymWMOKYuvgg0GPIP2RlLw7+zacfw9915VFiLpKSPrD48YU3p9jamIUeYb2aEDHpQK3rH4JUeAjdWV+a0mi0xWLjFzrVFc3R3jyUPAoxLNHLxzmb8+55pevA1JPUEYY2dolGBnZ7eXBAOIkHgEFlqqRxp4TLXoQR98eESYwrvaSV2YA11IuAJHF4bBI1pUfuUO7KiIDhacVi8VfNu5lAw8M1tInZk4aYLK6sw8L7XKq5hfZs="
      on:
        tags: true
        distributions: sdist
      skip_upload_docs: true

cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
