sudo: false
language: python
os: linux
install:
- &upgrade_python_toolset pip install --upgrade pip setuptools wheel
- &install_test_deps pip install --upgrade pytest pytest-sugar
- &install_deps pip install -r CI_REQUIREMENTS.txt
- pip install --upgrade pytest-cov coveralls

_helpers:
- &install_cython pip install --upgrade Cython
- &build_package python setup.py bdist_wheel
- &install_built pip install advanced_descriptors --no-index -f dist
- &test_no_cov  py.test -vv test
- &test_cythonized
  install:
  - *upgrade_python_toolset
  - *install_test_deps
  - *install_deps
  - *install_cython
  script:
  - *build_package
  - *install_built
  - *test_no_cov
  after_success: skip

script:
- pip install -e .
- py.test -vv --cov-config .coveragerc --cov-report= --cov=advanced_descriptors test
- coverage report -m --fail-under 89
after_success:
- coveralls

jobs:
  fast_finish: true
  include:
  - stage: test
    name: "Python 2.7"
    python: 2.7
  - stage: test
    name: "Python 3.4"
    python: 3.4
  - stage: test
    name: "Python 3.5"
    python: 3.5
  - stage: test
    name: "Python 3.6"
    python: 3.6
  - stage: test
    name: "Python 3.7"
    python: 3.7
    dist: xenial
    sudo: true
  - stage: test
    name: "PyPy"
    python: pypy
  - stage: test
    name: "PyPy3"
    python: pypy3.5

  - stage: Static analisys
    name: "PyLint"
    python: 3.6
    services: []
    install:
    - *upgrade_python_toolset
    - *install_deps
    - pip install --upgrade "pylint < 2.0"
    script:
    - pylint advanced_descriptors
    after_success: skip
  - stage: Static analisys
    name: "Bandit"
    python: 3.6
    services: []
    install:
    - *upgrade_python_toolset
    - pip install --upgrade bandit
    script:
    - bandit -r advanced_descriptors
    after_success: skip
  - stage: Static analisys
    name: "MyPy"
    python: 3.7
    dist: xenial
    sudo: true
    services: []
    install:
    - *upgrade_python_toolset
    - *install_deps
    - pip install --upgrade "mypy >= 0.620"
    script:
    - mypy --strict advanced_descriptors
    after_success: skip

  - stage: Test cythonized
    name: "Python 3.4"
    python: 3.4
    <<: *test_cythonized
  - stage: Test cythonized
    name: "Python 3.5"
    python: 3.5
    <<: *test_cythonized
  - stage: Test cythonized
    name: "Python 3.6"
    python: 3.6
    <<: *test_cythonized
  - stage: Test cythonized
    name: "Python 3.7"
    python: 3.7
    dist: xenial
    sudo: true
    <<: *test_cythonized

  - stage: Code style check
    name: "PEP8"
    python: 3.6
    install:
    - *upgrade_python_toolset
    - pip install --upgrade flake8
    script:
    - flake8
    after_success: skip
  - stage: Code style check
    name: "PEP257"
    python: 3.6
    install:
    - *upgrade_python_toolset
    - pip install --upgrade pydocstyle
    script:
    - pydocstyle advanced_descriptors
    after_success: skip

  - stage: deploy
    # This prevents job from appearing in test plan unless commit is tagged:
    if: tag IS present
    # Run on pypy to build not cythonized wheel
    python: pypy3.5
    services:
    - docker
    install:
    - *upgrade_python_toolset
    script:
    - ./tools/run_docker.sh "advanced_descriptors"
    before_deploy:
    - pip install -r build_requirements.txt
    - *build_package
    deploy:
    - provider: pypi
      # `skip_cleanup: true` is required to preserve binary wheels, built
      # inside of manylinux1 docker container during `script` step above.
      skip_cleanup: true
      user: penguinolog
      password:
        secure: "mG8p4UUzpz9wBdbif68NunjLp3rSED/OJw2Rh1nLBSSNcKtRBVEW4Gm/KYfHHc+kXVB66Nkda+T214kx4WhDk7lVRDKVu7ej0ze2mJX9iYmxhjOt7dcldostPAT8ZFfIvxEpS3UYGCPRbWTdOeeTe3wqz7/boVjC4DZu82nTarBJzApEn5ivtVHMs9bCedmk9Potb3FOiOscjkmEiKSllVQhgHnE/WPBOkfsaSaTCQKeTnqcCqJehNo4ki0cbmtAMpdPoR4DxAlHFK9jFD/W5Pm8s3UMkCer7vTwImINYICuibAIKEKcHdSHXOWJ6FoT21mJdgTWoZQGlAAKw8KV9R8dM6bNazV9iJbM3qUTUEJzyb08miRUf6iKxoPR1MpfqxuZ+ExGHfb0gX/Nu75aNxCSTbQ1YJD/oeXaqRQwpeGmW8vAXB9JSThfiEafymWMOKYuvgg0GPIP2RlLw7+zacfw9915VFiLpKSPrD48YU3p9jamIUeYb2aEDHpQK3rH4JUeAjdWV+a0mi0xWLjFzrVFc3R3jyUPAoxLNHLxzmb8+55pevA1JPUEYY2dolGBnZ7eXBAOIkHgEFlqqRxp4TLXoQR98eESYwrvaSV2YA11IuAJHF4bBI1pUfuUO7KiIDhacVi8VfNu5lAw8M1tInZk4aYLK6sw8L7XKq5hfZs="
      on:
        tags: true
        distributions: sdist
      skip_upload_docs: true

cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
