sudo: false
language: python
os: linux
install:
  - &upgrade_python_toolset pip install --upgrade pip setuptools wheel
  - pip install --upgrade pytest pytest-sugar
  - &install_deps pip install -r CI_REQUIREMENTS.txt
  - pip install --upgrade pytest-cov coveralls

_python:
  - &python27
    name: "Python 2.7"
    python: 2.7
  - &pypy
    name: "PyPy"
    python: pypy
  - &python34
    name: "Python 3.4"
    python: "3.4"
  - &python35
    name: "Python 3.5"
    python: "3.5"
  - &python36
    name: "Python 3.6"
    python: "3.6"
  - &python37
    name: "Python 3.7"
    python: "3.7"
    dist: xenial
    sudo: true
  - &pypy3
    name: "PyPy3"
    python: "pypy3.5"

_helpers:
  - &build_package python setup.py bdist_wheel

  - &static_analysis
    stage: Static analysis
    <<: *python36
    after_success: skip

  - &code_style_check
    stage: Code style check
    <<: *python36
    after_success: skip

script:
  - pip install -e .
  - py.test -vv --cov-config .coveragerc --cov-report= --cov=advanced_descriptors test
  - coverage report -m --fail-under 89
after_success:
  - coveralls

jobs:
  fast_finish: true
  include:
    - <<: *static_analysis
      name: "PyLint"
      install:
        - *upgrade_python_toolset
        - *install_deps
        - pip install --upgrade "pylint < 2.0"
      script:
        - pylint advanced_descriptors
    - <<: *static_analysis
      name: "Bandit"
      install:
        - *upgrade_python_toolset
        - pip install --upgrade bandit
      script:
        - bandit -r advanced_descriptors
    - <<: *static_analysis
      name: "MyPy"
      install:
        - *upgrade_python_toolset
        - *install_deps
        - pip install --upgrade "mypy >= 0.670"
      script:
        - mypy --strict advanced_descriptors
    - <<: *static_analysis
      name: "PEP8"
      install:
        - *upgrade_python_toolset
        - pip install --upgrade flake8 flake8-bugbear
      script:
        - flake8

    #  - <<: *code_style_check
    #    name: "PEP257"
    #    install:
    #    - *upgrade_python_toolset
    #    - pip install --upgrade pydocstyle
    #    script:
    #    - pydocstyle advanced_descriptors

    - stage: test
      <<: *python27
    - stage: test
      <<: *pypy
    - stage: test
      <<: *python34
    - stage: test
      <<: *python35
    - stage: test
      <<: *python36
    - stage: test
      <<: *python37
    - stage: test
      <<: *pypy3

    - stage: deploy
      # This prevents job from appearing in test plan unless commit is tagged:
      if: tag IS present
      <<: *pypy
      name: Build universal bdist_wheel. Deploy bdist and sdist.
      services: []
      install:
        - *upgrade_python_toolset
        - pip install -r build_requirements.txt
      script:
        - *build_package
      before_deploy: []
      deploy:
        - provider: pypi
          # `skip_cleanup: true` is required to preserve binary wheels, built
          # inside of manylinux1 docker container during `script` step above.
          skip_cleanup: true
          user: penguinolog
          password:
            secure: "mG8p4UUzpz9wBdbif68NunjLp3rSED/OJw2Rh1nLBSSNcKtRBVEW4Gm/KYfHHc+kXVB66Nkda+T214kx4WhDk7lVRDKVu7ej0ze2mJX9iYmxhjOt7dcldostPAT8ZFfIvxEpS3UYGCPRbWTdOeeTe3wqz7/boVjC4DZu82nTarBJzApEn5ivtVHMs9bCedmk9Potb3FOiOscjkmEiKSllVQhgHnE/WPBOkfsaSaTCQKeTnqcCqJehNo4ki0cbmtAMpdPoR4DxAlHFK9jFD/W5Pm8s3UMkCer7vTwImINYICuibAIKEKcHdSHXOWJ6FoT21mJdgTWoZQGlAAKw8KV9R8dM6bNazV9iJbM3qUTUEJzyb08miRUf6iKxoPR1MpfqxuZ+ExGHfb0gX/Nu75aNxCSTbQ1YJD/oeXaqRQwpeGmW8vAXB9JSThfiEafymWMOKYuvgg0GPIP2RlLw7+zacfw9915VFiLpKSPrD48YU3p9jamIUeYb2aEDHpQK3rH4JUeAjdWV+a0mi0xWLjFzrVFc3R3jyUPAoxLNHLxzmb8+55pevA1JPUEYY2dolGBnZ7eXBAOIkHgEFlqqRxp4TLXoQR98eESYwrvaSV2YA11IuAJHF4bBI1pUfuUO7KiIDhacVi8VfNu5lAw8M1tInZk4aYLK6sw8L7XKq5hfZs="
          on:
            tags: true
            distributions: sdist
          skip_upload_docs: true
          skip_existing: true

cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
