# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job: 'PyLint'
  pool:
    vmIMage: 'VS2017-Win2016'
  strategy:
    maxParallel: 1
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'

  - script: |
      python -m pip install --upgrade pip
      pip install -U setuptools
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install -U pylint
      pylint -f msvs advanced_descriptors
    displayName: 'PyLint'

- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_34', python: '3.4', architecture: 'x64', kind: 'native'}
- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_35', python: '3.5', architecture: 'x64', kind: 'native'}
- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_36', python: '3.6', architecture: 'x64', kind: 'native'}
- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_37', python: '3.7', architecture: 'x64', kind: 'native'}

- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_34', python: '3.4', architecture: 'x64', kind: 'cython'}
- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_34', python: '3.4', architecture: 'x86', kind: 'cython'}
- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_35', python: '3.5', architecture: 'x64', kind: 'cython'}
- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_35', python: '3.5', architecture: 'x86', kind: 'cython'}
- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_36', python: '3.6', architecture: 'x64', kind: 'cython'}
- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_36', python: '3.6', architecture: 'x86', kind: 'cython'}
- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_37', python: '3.7', architecture: 'x64', kind: 'cython'}
- template: .azure_pipelines/run_tests.yml
  parameters: {name: 'Python_37', python: '3.7', architecture: 'x86', kind: 'cython'}
